services:
  app:
    build: ./app
    container_name: neon-proxy-app
    ports:
      - "7500:7500"
    environment:
      - APP_PORT=7500
      - INTERNAL_API_URL=http://internal-api:9100
    depends_on:
      - internal-api

  internal-api:
    build: ./internal-api
    container_name: neon-internal
    expose:
      - "9100"
    environment:
      - API_PORT=9100
